/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexOldRouteImport } from './routes/index-old'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRoleIdRouteImport } from './routes/apply.$roleId'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppDashboardOldRouteImport } from './routes/_app.dashboard-old'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppRolesIndexRouteImport } from './routes/_app.roles.index'
import { Route as AppApplicantsIndexRouteImport } from './routes/_app.applicants.index'
import { Route as AppRolesRoleIdRouteImport } from './routes/_app.roles.$roleId'
import { Route as AppApplicantsApplicantIdRouteImport } from './routes/_app.applicants.$applicantId'

const IndexOldRoute = IndexOldRouteImport.update({
  id: '/index-old',
  path: '/index-old',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoleIdRoute = ApplyRoleIdRouteImport.update({
  id: '/apply/$roleId',
  path: '/apply/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardOldRoute = AppDashboardOldRouteImport.update({
  id: '/dashboard-old',
  path: '/dashboard-old',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicantsIndexRoute = AppApplicantsIndexRouteImport.update({
  id: '/applicants/',
  path: '/applicants/',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoleIdRoute = AppRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AppRoute,
} as any)
const AppApplicantsApplicantIdRoute =
  AppApplicantsApplicantIdRouteImport.update({
    id: '/applicants/$applicantId',
    path: '/applicants/$applicantId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index-old': typeof IndexOldRoute
  '/dashboard': typeof AppDashboardRoute
  '/dashboard-old': typeof AppDashboardOldRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/apply/$roleId': typeof ApplyRoleIdRoute
  '/applicants/$applicantId': typeof AppApplicantsApplicantIdRoute
  '/roles/$roleId': typeof AppRolesRoleIdRoute
  '/applicants/': typeof AppApplicantsIndexRoute
  '/roles/': typeof AppRolesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index-old': typeof IndexOldRoute
  '/dashboard': typeof AppDashboardRoute
  '/dashboard-old': typeof AppDashboardOldRoute
  '/settings': typeof AppSettingsRoute
  '/templates': typeof AppTemplatesRoute
  '/apply/$roleId': typeof ApplyRoleIdRoute
  '/applicants/$applicantId': typeof AppApplicantsApplicantIdRoute
  '/roles/$roleId': typeof AppRolesRoleIdRoute
  '/applicants': typeof AppApplicantsIndexRoute
  '/roles': typeof AppRolesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/index-old': typeof IndexOldRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/dashboard-old': typeof AppDashboardOldRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/apply/$roleId': typeof ApplyRoleIdRoute
  '/_app/applicants/$applicantId': typeof AppApplicantsApplicantIdRoute
  '/_app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/_app/applicants/': typeof AppApplicantsIndexRoute
  '/_app/roles/': typeof AppRolesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/index-old'
    | '/dashboard'
    | '/dashboard-old'
    | '/settings'
    | '/templates'
    | '/apply/$roleId'
    | '/applicants/$applicantId'
    | '/roles/$roleId'
    | '/applicants/'
    | '/roles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/index-old'
    | '/dashboard'
    | '/dashboard-old'
    | '/settings'
    | '/templates'
    | '/apply/$roleId'
    | '/applicants/$applicantId'
    | '/roles/$roleId'
    | '/applicants'
    | '/roles'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/index-old'
    | '/_app/dashboard'
    | '/_app/dashboard-old'
    | '/_app/settings'
    | '/_app/templates'
    | '/apply/$roleId'
    | '/_app/applicants/$applicantId'
    | '/_app/roles/$roleId'
    | '/_app/applicants/'
    | '/_app/roles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  IndexOldRoute: typeof IndexOldRoute
  ApplyRoleIdRoute: typeof ApplyRoleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index-old': {
      id: '/index-old'
      path: '/index-old'
      fullPath: '/index-old'
      preLoaderRoute: typeof IndexOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$roleId': {
      id: '/apply/$roleId'
      path: '/apply/$roleId'
      fullPath: '/apply/$roleId'
      preLoaderRoute: typeof ApplyRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard-old': {
      id: '/_app/dashboard-old'
      path: '/dashboard-old'
      fullPath: '/dashboard-old'
      preLoaderRoute: typeof AppDashboardOldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles/': {
      id: '/_app/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applicants/': {
      id: '/_app/applicants/'
      path: '/applicants'
      fullPath: '/applicants/'
      preLoaderRoute: typeof AppApplicantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles/$roleId': {
      id: '/_app/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof AppRolesRoleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/applicants/$applicantId': {
      id: '/_app/applicants/$applicantId'
      path: '/applicants/$applicantId'
      fullPath: '/applicants/$applicantId'
      preLoaderRoute: typeof AppApplicantsApplicantIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDashboardOldRoute: typeof AppDashboardOldRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppApplicantsApplicantIdRoute: typeof AppApplicantsApplicantIdRoute
  AppRolesRoleIdRoute: typeof AppRolesRoleIdRoute
  AppApplicantsIndexRoute: typeof AppApplicantsIndexRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDashboardOldRoute: AppDashboardOldRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppApplicantsApplicantIdRoute: AppApplicantsApplicantIdRoute,
  AppRolesRoleIdRoute: AppRolesRoleIdRoute,
  AppApplicantsIndexRoute: AppApplicantsIndexRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  IndexOldRoute: IndexOldRoute,
  ApplyRoleIdRoute: ApplyRoleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
